/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aimyskin_asentinel_Asentinel */

#ifndef _Included_com_aimyskin_asentinel_Asentinel
#define _Included_com_aimyskin_asentinel_Asentinel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aimyskin_asentinel_Asentinel
 * Method:    generateToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aimyskin_asentinel_Asentinel_generateToken
  (JNIEnv *, jobject);

/*
 * Class:     com_aimyskin_asentinel_Asentinel
 * Method:    verifyToken
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_aimyskin_asentinel_Asentinel_verifyToken
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
